name: "Test #907"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Go-1_14:
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - name: Module cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: go-mod-cache
      with:
        path: ~/go/pkg/mod
        key: windows-latest-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
    - name: Run tests
      env:
        GOARCH: "386"
      run: go test -failfast -count=10000 -run=TestHandlerTestSuite/TestNoDropsOnDelegate
  Go-1_15:
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - name: Module cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: go-mod-cache
      with:
        path: ~/go/pkg/mod
        key: windows-latest-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
    - name: Run tests
      env:
        GOARCH: "386"
      run: go test -failfast -count=10000 -run=TestHandlerTestSuite/TestNoDropsOnDelegate
